<?php if(!defined('BASEPATH')) exit('No direct script access allowed');

class Survey_model extends CI_Model
{
	function showAll($tglawal,$tglakhir){
		if($tglawal==NULL && $tglakhir==NULL){
			$query_mbr = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr");
	    	$query_mbr_duplicate = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi_duplicate val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr");
	    	$query_skm = $this->db->query("SELECT skm.nik_rt as nik, skm.nama_kk as nama, '-' as kk, skm.kecamatan, skm.kelurahan, skm.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'SKM' as jenis_data, '-' as kk,'-' as id FROM validasi_skm val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN tbl_users usr ON val.val_id = usr.userId INNER JOIN skm skm ON val.tgl_survey = skm.jadwal_survey AND val.nik_rt=skm.nik_rt AND val.nik_skm=skm.nik LEFT JOIN dokumentasi_skm as dok ON val.tgl_survey = dok.tgl_survey and dok.nik_rt = val.nik_rt and val.nik_skm = dok.nik_skm");
		}else{
			$query_mbr = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."' ORDER BY val.tgl_survey ASC");
	    	$query_mbr_duplicate = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi_duplicate val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."' ORDER BY val.tgl_survey ASC");
	    	$query_skm = $this->db->query("SELECT skm.nik_rt as nik, skm.nama_kk as nama, '-' as kk, skm.kecamatan, skm.kelurahan, skm.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'SKM' as jenis_data, '-' as kk,'-' as id FROM validasi_skm val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN tbl_users usr ON val.val_id = usr.userId INNER JOIN skm skm ON val.tgl_survey = skm.jadwal_survey AND val.nik_rt=skm.nik_rt AND val.nik_skm=skm.nik LEFT JOIN dokumentasi_skm as dok ON val.tgl_survey = dok.tgl_survey and dok.nik_rt = val.nik_rt and val.nik_skm = dok.nik_skm WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."' ORDER BY val.tgl_survey ASC");
		}

	    $mbr = $query_mbr->result_array();
	    $mbr_duplicate = $query_mbr_duplicate->result_array();
	    $skm = $query_skm->result_array();
	    $query = array_merge($mbr,$mbr_duplicate,$skm);
	    return $query;
	}

    function countAll($tglawal,$tglakhir){
	    if($tglawal==NULL && $tglakhir==NULL){
			$query_mbr = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr");
	    	$query_mbr_duplicate = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi_duplicate val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr");
	    	$query_skm = $this->db->query("SELECT skm.nik_rt as nik, skm.nama_kk as nama, '-' as kk, skm.kecamatan, skm.kelurahan, skm.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'SKM' as jenis_data, '-' as kk,'-' as id FROM validasi_skm val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN tbl_users usr ON val.val_id = usr.userId INNER JOIN skm skm ON val.tgl_survey = skm.jadwal_survey AND val.nik_rt=skm.nik_rt AND val.nik_skm=skm.nik LEFT JOIN dokumentasi_skm as dok ON val.tgl_survey = dok.tgl_survey and dok.nik_rt = val.nik_rt and val.nik_skm = dok.nik_skm");
		}else{
			$query_mbr = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."'");
	    	$query_mbr_duplicate = $this->db->query("SELECT mbr.no as id, mbr.nik, mbr.nama, mbr.kk, mbr.kecamatan, mbr.kelurahan, mbr.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'MBR' as jenis_data FROM validasi_duplicate val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN mbr2018 mbr ON val.id_mbr=mbr.no INNER JOIN tbl_users usr ON val.val_id = usr.userId LEFT JOIN dokumentasi_mbr as dok ON val.id_mbr = dok.id_mbr WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."'");
	    	$query_skm = $this->db->query("SELECT skm.nik_rt as nik, skm.nama_kk as nama, '-' as kk, skm.kecamatan, skm.kelurahan, skm.alamat, sur.nama_surveyor, val.tgl_survey, usr.name, val.val_tgl, val.ket, val.catatan, dok.foto_depan_rumah, dok.foto_kondisi_rumah, dok.foto_selfie, 'SKM' as jenis_data, '-' as kk,'-' as id FROM validasi_skm val INNER JOIN surveyor sur ON val.surveyor_id = sur.id_surveyor INNER JOIN tbl_users usr ON val.val_id = usr.userId INNER JOIN skm skm ON val.tgl_survey = skm.jadwal_survey AND val.nik_rt=skm.nik_rt AND val.nik_skm=skm.nik LEFT JOIN dokumentasi_skm as dok ON val.tgl_survey = dok.tgl_survey and dok.nik_rt = val.nik_rt and val.nik_skm = dok.nik_skm WHERE val.tgl_survey>='".$tglawal."' AND val.tgl_survey <='".$tglakhir."'");
		}
	    $mbr = $query_mbr->result_array();
	    $mbr_duplicate = $query_mbr_duplicate->result_array();
	    $skm = $query_skm->result_array();
	    $query = array_merge($mbr,$mbr_duplicate,$skm);
	    return count($query);
    }
}